project/app.py
from flask import Flask, render_template
from project.common.database import Database
import os


app = Flask(__name__)
app.config.from_object("project.config")
app.secret_key = os.environ.get("app.secret_key")


@app.before_first_request
def database_init():
    Database.initialize()


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/about")
def about():
    return render_template("about.html")


from project.models.users.views import user_blueprint
from project.models.alerts.views import alert_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

project/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from project.models.alerts.alert import Alert
from project.models.items.item import Item
import project.models.alerts.errors as Errors
import project.models.users.decorators as decorators

alert_blueprint = Blueprint("alerts", __name__)


@alert_blueprint.route("/add", methods=["GET", "POST"])
@decorators.login_required
def add_alert():
    if request.method == "POST":
        name = request.form["name"]
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        try:
            if Item.url_validation(url):
                item = Item(name, url)
                item.save_item_data()
                alert = Alert(session['email'], item._id, price_limit)
                alert.check_price()
                return redirect(url_for("users.user_alerts"))
        except Errors.AlertErrors as e:
            return e.message

    return render_template("alerts/new_alert.html")


@alert_blueprint.route("/<string:alert_id>")
@decorators.login_required
def check_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template("alerts/alert.html", alert=alert)


@alert_blueprint.route("/check_price/<string:alert_id>")
@decorators.login_required
def check_actual_price(alert_id):
    Alert.find_by_id(alert_id).check_price()
    return redirect(url_for('.check_alert', alert_id=alert_id))


@alert_blueprint.route("/edit/<string:alert_id>", methods=["GET", "POST"])
@decorators.login_required
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == "POST":
        price_limit = float(request.form["price_limit"])

        alert.price_limit = price_limit
        alert.save_alert_data()
        return redirect(url_for('users.user_alerts'))

    return render_template("alerts/edit_alert.html", alert=alert)


@alert_blueprint.route("/activate/<string:alert_id>")
@decorators.login_required
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route("/deactivate/<string:alert_id>")
@decorators.login_required
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route("/delete/<string:alert_id>")
@decorators.login_required
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))

project/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint("items", __name__)


@item_blueprint.route("/item/<string:name>")
def item(name):
    pass

project/models/users/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from project.models.users.user import User
import project.models.users.errors as Errors
import project.models.users.decorators as decorators

user_blueprint = Blueprint("users", __name__)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.register(email, password):
                session["email"] = email
                return redirect(url_for(".user_alerts"))
        except Errors.UserErrors as e:
            return e.message

    return render_template("users/register.html")


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.user_validation(email, password):
                session["email"] = email
                return redirect(url_for(".user_alerts"))
        except Errors.UserErrors as e:
            return e.message

    return render_template("users/login.html")


@user_blueprint.route("/alerts")
@decorators.login_required
def user_alerts():
    user = User.find_by_email(session["email"])
    alerts = user.get_alerts()
    return render_template("users/alerts.html", alerts=alerts)


@user_blueprint.route("/alerts_list/<string:user_id>")
def alerts_list(user_id):
    pass


@user_blueprint.route("/logout")
def logout():
    session["email"] = None
    return redirect(url_for("home"))

project/templates/about.html
{% extends "layout.html" %}

{% block content %}

    <div class="jumbotron">
      <h2>Price tracker for products available on ceneo.pl</h2><br>
      <p>With this app you can track the prices of your desired products available on ceneo.pl.
          After registration, you will get alerts on your email when prices of selected items will drop below a
          specified limit.</p>
    </div>


{% endblock %}

project/templates/alerts/alert.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
        <h2>Alert for {{ alert.item.name }}</h2>
    </div>

    <p>Last price (PLN): <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked: {{ alert.last_check.strftime("%d-%m-%Y at %H:%M") }}</p>

    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-info" role="button" href="{{ alert.item.url }}" target="_blank">Visit site</a>
            <a class="btn btn-primary" role="button" href="{{ url_for('alerts.check_actual_price', alert_id=alert._id) }}">Check actual price</a>
            <a class="btn btn-warning" role="button" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">Edit alert</a>
            {% if alert.active %}
                <a class="btn btn-danger" role="button" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}">Deactivate alert</a>
            {% else %}
                <a class="btn btn-success" role="button" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}">Activate alert</a>
                <a class="btn btn-danger" role="button" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">Delete alert</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

project/templates/alerts/edit_alert.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
        <h2>Edit Alert</h2>
    </div>

    <div class="form-size">
        <form method="POST">
            <div class="form-group">
                <label for="name">Item name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="url">Item URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.item.url }}" disabled>
            </div>
            <div class="form-group">
                <label for="price_limit">Price limit</label>
                <input type="number" class="form-control" id="price_limit" name="price_limit" placeholder="PLN"
                       value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp">
                <p id="priceLimitHelp" class="help-block">You will get an e-mail when price of the item will fall below limit</p>
            </div>
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    </div>

{% endblock %}

project/templates/alerts/new_alert.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
        <h2>Add new alert!</h2>
    </div>

    <div class="form-size">
        <form method="POST">
            <div class="form-group">
                <label for="name">Item name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">Item URL (copy from https://www.ceneo.pl)</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Price limit</label>
                <input type="number" class="form-control" id="price_limit" name="price_limit" placeholder="PLN"
                    aria-describedby="priceLimitHelp">
                <p id="priceLimitHelp" class="help-block">You will get an e-mail when price of the item will fall below limit</p>
            </div>
            <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>

{% endblock %}

project/templates/home.html
{% extends "layout.html" %}

{% block content %}

    <div class="jumbotron">
      <h2>Price Tracker</h2><br>
      <p>Track prices of items that interest you!</p>
      <p>Just sign up and start!</p><br>
      <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Sign up!</a></p>
    </div>

{% endblock %}

project/templates/html_links.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}">

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price tracker</title>

    {% include "html_links.html" %}

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" title="Home">Price tracker</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('about') }}">About</a></li>
            </ul>
            {% if session["email"] %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-alert"></span> Alerts</a></li>
                <li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

project/templates/users/alerts.html
{% extends "layout.html" %}
{% block content %}
    <div class="page-header">
        <h1>Your alerts</h1>
    </div>

    <div class="list-group">
        {% for alert in alerts %}
            <a href="{{ url_for('alerts.check_alert', alert_id = alert._id) }}" class="list-group-item {{'list-group-item-warning' if not alert.active else ''}}">
                <h3 class="list-group-item-heading">
                    {{ "<span class='glyphicon glyphicon-remove-circle'></span>" |safe if not alert.active else '' }} Alert for: {{ alert.item.name }}</h3>
                <p class="list-group-item-text">Your price limit: {{ alert.price_limit }} PLN <br>
                    Latest price (PLN): <strong>{{ alert.item.price }}</strong> <small>(checked on {{ alert.last_check.strftime("%d-%m-%Y at %H:%M") }})</small> </p>
            </a>
        {% endfor %}
    </div>
    <a class="btn btn-success" href="{{ url_for('alerts.add_alert') }}">New alert</a>

{% endblock %}

project/templates/users/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="form-size">
        <form method="POST" action="{{ url_for('users.login') }}">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Log in</button>
        </form>
    </div>
{% endblock %}

project/templates/users/register.html
{% extends "layout.html" %}

{% block content %}
    <div class="form-size">
        <form method="POST" action="{{ url_for('users.register') }}">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Sign up</button>
        </form>
    </div>
{% endblock %}